# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import game_service_pb2 as game__service__pb2


class Game_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.send_chat_message = channel.unary_unary(
                '/game_service.Game_service/send_chat_message',
                request_serializer=game__service__pb2.Message.SerializeToString,
                response_deserializer=game__service__pb2.Empty.FromString,
                )
        self.get_chat_message = channel.unary_stream(
                '/game_service.Game_service/get_chat_message',
                request_serializer=game__service__pb2.Empty.SerializeToString,
                response_deserializer=game__service__pb2.Message.FromString,
                )


class Game_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def send_chat_message(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_chat_message(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Game_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'send_chat_message': grpc.unary_unary_rpc_method_handler(
                    servicer.send_chat_message,
                    request_deserializer=game__service__pb2.Message.FromString,
                    response_serializer=game__service__pb2.Empty.SerializeToString,
            ),
            'get_chat_message': grpc.unary_stream_rpc_method_handler(
                    servicer.get_chat_message,
                    request_deserializer=game__service__pb2.Empty.FromString,
                    response_serializer=game__service__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'game_service.Game_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Game_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def send_chat_message(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game_service.Game_service/send_chat_message',
            game__service__pb2.Message.SerializeToString,
            game__service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_chat_message(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/game_service.Game_service/get_chat_message',
            game__service__pb2.Empty.SerializeToString,
            game__service__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
