# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12game_service.proto\x12\x0cgame_service\"\x07\n\x05\x45mpty\"&\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t2\x95\x01\n\x0cGame_service\x12\x41\n\x11send_chat_message\x12\x15.game_service.Message\x1a\x13.game_service.Empty\"\x00\x12\x42\n\x10get_chat_message\x12\x13.game_service.Empty\x1a\x15.game_service.Message\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=36
  _EMPTY._serialized_end=43
  _MESSAGE._serialized_start=45
  _MESSAGE._serialized_end=83
  _GAME_SERVICE._serialized_start=86
  _GAME_SERVICE._serialized_end=235
# @@protoc_insertion_point(module_scope)
